project:
  type: website

website:
  title: "Amelia E. H. Bridges"
  site-url: https://www.ameliabridges.com
  favicon: Images/favicon.ico
  open-graph: true
  twitter-card: 
    creator: "@Amelia_Bridges"
    image: Images/Sea_sunset.ico
    description: 
      "Professional website for Dr Amelia Bridges, postdoctoral benthic ecologist and National Geographic Explorer"
  navbar:
    logo: Images/favicon.ico
    foreground: "#003333"
    background: "#C1CFCE"
    right:
      - text: "Home"
        href: index.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Consultancy"
        href: consultancy.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Media"
        href: media.qmd
      - icon: github
        href: https://github.com/ameliabridges
      - icon: twitter
        href: https://twitter.com/Amelia_Bridges
      - icon: flower2
        href: https://orcid.org/my-orcid?orcid=0000-0002-1422-9637
  # body-footer: | 
  #   Testing this option <https://example.com>

format:
  html:
    theme: 
      dark: [solar, CustomStyle_dark.scss]
      light: [solar, CustomStyle_light.scss]
    linestretch: 1.7
    css: styles.css
    toc: false



