project:
  type: website

website:
  title: "AEHB"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Consultancy"
        href: consultancy.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Media"
        href: media.qmd
      - icon: fa fa-github
        href: https://github.com/ameliabridges
      - icon: fa fa-twitter
        href: https://twitter.com/Amelia_Bridges

format:
  html:
    theme: 
      light: litera
      dark: solar
    css: styles.css
    toc: true



